services:
  # A Node.js web service
  - type: web
    name: task-management-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: task-management-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: task-management-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: task-management-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: task-management-db
          property: password
      - key: BASE_URL
        value: https://task-management-system.onrender.com
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password

databases:
  - name: task-management-db
    databaseName: task_management_db
    user: task_management_user
    plan: free 