services:
  - type: web
    name: task-management-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://task-management-system.onrender.com

databases:
  - name: task-management-db
    databaseName: task_management_db
    user: task_management_user
    plan: free 